apiVersion: apps/v1
kind: Deployment
metadata:
  name: w2
spec:
  selector:
    matchLabels:
      app: w2
  replicas: 1
  template:
    metadata:
      labels:
        app: w2
    spec:
      containers:
      - name: agent-run
        image: ethomson/azure-pipelines-k8s-win32
        command: [ 'powershell', '/data/agent/k8s-run.ps1' ]
        volumeMounts:
        - name: share
          mountPath: 'C:/tmp'
        - name: dockersock
          mountPath: '\\.\pipe\docker_engine'
        env:
        - name: IMAGE
          value: "ethomson/rust-build-win32:latest"
        - name: SHARE_DIR
          value: "C:\\Tmp"
        - name: AZURE_PIPELINES_URL
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: url
        - name: AZURE_PIPELINES_POOL
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pool
        - name: AZURE_PIPELINES_PAT
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pat
      volumes:
      - name: share
        hostPath:
          path: 'C:/tmp'
      - name: dockersock
        hostPath:
          path: '\\.\pipe\docker_engine'
