apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux1
spec:
  selector:
    matchLabels:
      app: linux1
  replicas: 5
  template:
    metadata:
      labels:
        app: linux1
    spec:
      containers:
      - name: agent-run
        image: ethomson/azure-pipelines-k8s-linux
        command: [ '/data/agent/k8s-run.sh' ]
        volumeMounts:
        - name: share
          mountPath: '/data/share'
        - name: dockersock
          mountPath: '/var/run/docker.sock'
        env:
        - name: IMAGE
          value: "ethomson/rust-build-linux:latest"
        - name: AZURE_PIPELINES_URL
          value: "https://dev.azure.com/rust-lang"
        - name: AZURE_PIPELINES_POOL
          value: "linux-private"
        - name: AZURE_PIPELINES_PAT
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pat
      volumes:
      - name: share
        hostPath:
          path: '/data/share'
      - name: dockersock
        hostPath:
          path: '/var/run/docker.sock'
