apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentw
spec:
  selector:
    matchLabels:
      app: agentw
  replicas: 1
  template:
    metadata:
      labels:
        app: agentw
    spec:
      containers:
      - name: agent-run
        image: ethomson/azure-pipelines-agent-win32
        command: [ 'powershell', '/data/agent/docker-run.ps1' ]
        volumeMounts:
        - name: share
          mountPath: 'C:/tmp'
        - name: dockersock
          mountPath: '\\.\pipe\docker_engine'
        env:
        - name: AZURE_PIPELINES_URL
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: url
        - name: AZURE_PIPELINES_POOL
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pool
        - name: AZURE_PIPELINES_PAT
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pat
      volumes:
      - name: share
        hostPath:
          path: 'C:/tmp'
      - name: dockersock
        hostPath:
          path: '\\.\pipe\docker_engine'
