apiVersion: apps/v1
kind: Deployment
metadata:
  name: win1
spec:
  selector:
    matchLabels:
      app: win1
  replicas: 5
  template:
    metadata:
      labels:
        app: win1
    spec:
      containers:
      - name: agent-run
        image: ethomson/azure-pipelines-k8s-win32
        command: [ 'powershell', '/data/agent/k8s-run.ps1' ]
        volumeMounts:
        - name: share
          mountPath: 'C:/tmp'
        - name: dockersock
          mountPath: '\\.\pipe\docker_engine'
        env:
        - name: IMAGE
          value: "ethomson/rust-build-win32:latest"
        - name: SHARE_DIR
          value: "C:\\Tmp"
        - name: AZURE_PIPELINES_URL
          value: "https://dev.azure.com/rust-lang"
        - name: AZURE_PIPELINES_POOL
          value: "windows-private"
        - name: AZURE_PIPELINES_PAT
          valueFrom:
            secretKeyRef:
              name: agentconfig
              key: pat
      volumes:
      - name: share
        hostPath:
          path: 'C:/tmp'
      - name: dockersock
        hostPath:
          path: '\\.\pipe\docker_engine'
